# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
version = "1.0.1"
title = "CAE CGNS Importer"
description = "Asset importer extension for importing CGNS files into Omniverse using the asset importer framework."
category = "CAE"
readme  = "docs/README.md"
keywords = ["kit", "cae", "cgns"]
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"

[dependencies]
"omni.cae.cgns" = {}
"omni.client" = {}
"omni.kit.tool.asset_importer" = {}
"omni.ui" = {}

[[python.module]]
name = "omni.cae.asset_importer.cgns"

[documentation]
pages = [
    "docs/README.md",
    "docs/CHANGELOG.md",
]

[[test]]

dependencies = [
    "omni.cae.testing",
    "omni.cae.sids"
]