# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
#  its affiliates is strictly prohibited.

[package]
title = "CAE VTK"
version = "1.2.0"
description = "Extension that provides VTK data delegate and VTK-specific operator commands."
category = "CAE"
changelog = "docs/CHANGELOG.md"
icon = "data/icon.png"
keywords = ["kit", "cae", "vtk"]
readme  = "docs/README.md"  # Path (relative to the root) or content of readme markdown file for UI
# repository = "https://github.com/NVIDIA-Omniverse/kit-app-template"  # URL of the extension source repository

[dependencies]
"omni.cae.data" = {}
"omni.cae.vtk_libs" = {}
"omni.cae.index" = {}

[[python.module]]
name = "omni.cae.vtk"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
